### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [evgenyneu/Cephalopod#2]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by evgenyneu** [comment]
Hi @lfarah, thanks for the reminder. I have updated the library to Swift 3.0. Let me know how it works for you.

**Comment by lfarah** [comment]
Thanks! 🎉

**Comment by evgenyneu** [comment]
No worries, closing the issue, feel free to reopen if necessary.
