### ISSUE TITLE
Integration with Objective C

### ISSUE THREAD

**Issue by aareeph** [evgenyneu/Cephalopod#3]
Hi 

Thanks for this wonderful library. I am trying to integrate this library in my project written in Objective C. I've successfully added the Swift code in my code but there's no impact on volume while trying different methods.

//self.BackgroundMusicPlayer => Name of my AVAudioPlayer

Cephalopod *cep = [[Cephalopod alloc] initWithPlayer:self.BackgroundMusicPlayer]; 
1)
        [cep fadeFromVolume:0 toVolume:1 duration:5 velocity:1 onFinished:^(BOOL finished) {
                        NSLog(@"Fading Done");
                    }];

2)
        [cep fadeInDuration:5 velocity:1 onFinished:^(BOOL finished) {
           NSLog(@"Fading Done");
        }];

Any help in this regards will be highly appreciated.

Thanks!

**Comment by aareeph** [comment]
Also, the BOOL **finished** variable is returning false.

**Comment by evgenyneu** [comment]
Hello @aareeph, thanks for reporting. I have just tested Cephalopod with ObjC for the first time, and it seems to work for me. Please see the sample project attached. 

[UsingCephalopodInObjC.zip](https://github.com/evgenyneu/Cephalopod/files/577468/UsingCephalopodInObjC.zip)


**ViewController.h**

```ObjectiveC
@interface ViewController : UIViewController

@property (strong, nonatomic) AVAudioPlayer *audioPlayer;
@property (strong, nonatomic) Cephalopod *cep;

@end
``` 

**ViewController.m**

```ObjectiveC
@implementation ViewController

- (void)viewDidLoad {
  [super viewDidLoad];
  
  NSError *error;
  NSString *soundFilePath = [NSString stringWithFormat:@"%@/squid.mp3",
                             [[NSBundle mainBundle] resourcePath]];
  NSURL *url = [NSURL fileURLWithPath:soundFilePath];
  self.audioPlayer = [[AVAudioPlayer alloc]
                      initWithContentsOfURL:url
                      error:&error];
  NSLog(@"Error %@",error);
  [self.audioPlayer prepareToPlay];
  [self.audioPlayer play];
  
  self.cep = [[Cephalopod alloc] initWithPlayer:self.audioPlayer];

  [self.cep fadeFromVolume:0 toVolume:1 duration:2 velocity:2 onFinished:^(BOOL finished) {
    if (finished) {
      NSLog(@"Fading Done Finished");
    } else {
      NSLog(@"Fading Done NOT finished");
    }
  }];
}

@end
```

Let me know how it goes.

**Comment by aareeph** [comment]
Hello @evgenyneu you're awesome. It worked very well for me. Here is the problematic line in my code. I was creating the object in the method instead of making it a strong nonatomic property.

Cephalopod *cep = [[Cephalopod alloc] initWithPlayer:self.BackgroundMusicPlayer];

Your library is also amazing.

Thanks!
Arif

**Comment by evgenyneu** [comment]
No worries, good luck with everything.

**Comment by aareeph** [comment]
Hi, me again :)

I need your suggestion regarding the following method.  In my case I am creating an Audio Player that has Play/Pause toggle button. If the user continuously tap on this button while the fading effect is in progress eventually the sound goes off. Repeatedly pausing/resuming the audio isn’t typical user behavior but I would like to know if there's any method in the SDK that invalidates the following method so I can call it on Pause.

[self.cep fadeFromVolume:1 toVolume:0 duration:5 velocity:2 onFinished:^(BOOL finished) {
    if (finished) {
      NSLog(@"Fading Done Finished");
    } else {
      NSLog(@"Fading Done NOT finished");
    }
  }];

What do you suggest?

Thanks!

**Comment by evgenyneu** [comment]
Hi @aareeph, good question. Yes, there is a `stop()` method that cancells the ongoing volume change. Thank you for bringing this up, I just realized that I forgot to mention this method in the readme. Let me know if it works for you.

**Comment by aareeph** [comment]
Hi @evgenyneu  it worked very well for me. Thanks!

**Comment by evgenyneu** [comment]
Awesome 👍
