### ISSUE TITLE
Fade out effect at the end of song

### ISSUE THREAD

**Issue by Otbivnoe** [evgenyneu/Cephalopod#5]
Is it possible to set a fade out event at the end of the song (without any additional times from my side)? For instance, I have a track (2:00 min) and I want to achieve a fade out effect during 10 second from 1:50 - 2:00.

**Comment by evgenyneu** [comment]
Hi, good question! This library does not have this kind of delayed fade-out, unfortunately. So one will need to trigger the fade out manually near the end of the song. Sorry :)
