### ISSUE TITLE
Newbee questions

### ISSUE THREAD

**Issue by JosepBernad** [evgenyneu/Cephalopod#9]
Hello, and first of all contratulations for this amazing repo!
I want to start an app I'm wondering a few aspects of it:
- The app will stream audio from a server over the network. Can this library work with AVPlayer instead of AVAudioPlayer?
- The way the app will be built, I will need to seek and crossfade through the audio file and crossfade between two different audio files. Is this possible with this library? 
My first idea was to create two instances of AVPlayer in order to crossfade them, is this a good method? If not, what do you recommend?

I've been developing iOS apps for a few years but this is my first audio-related project and I'm a bit lost.

Thanks guys!

**Comment by evgenyneu** [comment]
Hi, 

> The app will stream audio from a server over the network. Can this library work with AVPlayer instead of AVAudioPlayer?

No, unfortunately, the library uses AVAudioPlayer.

> The way the app will be built, I will need to seek and crossfade through the audio file and crossfade between two different audio files. Is this possible with this library?

I think it should work, you can create two instances of Cephalopod for each file, then fade out the first one, and fade in the second one.

**Comment by JosepBernad** [comment]
> No, unfortunately, the library uses AVAudioPlayer.

Oh, thanks anyways!
